version: "3.9"

services:
  nifi:
    image: apache/nifi:1.25.0
    container_name: nifi
    ports:
      - "8443:8443"      # UI HTTPS
    environment:
      NIFI_WEB_HTTPS_HOST: "0.0.0.0"
      NIFI_WEB_HTTPS_PORT: "8443"
      SINGLE_USER_CREDENTIALS_USERNAME: "admin"
      SINGLE_USER_CREDENTIALS_PASSWORD: "fia@projeto-final"
    volumes:
      - nifi_data:/opt/nifi/nifi-current/state
    depends_on:
      - minio
    networks: [lab]

  minio:
    image: minio/minio:latest
    container_name: minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: "minio"
      MINIO_ROOT_PASSWORD: "minio123"
    ports:
      - "9000:9000"   # S3 API
      - "9001:9001"   # Console
    volumes:
      - minio_data:/data
    networks: [lab]

  mc:  # cliente minio para criar bucket automaticamente
    image: minio/mc:latest
    depends_on: [minio]
    entrypoint: >
      /bin/sh -c "
      sleep 3 &&
      mc alias set local http://minio:9000 minio minio123 &&
      mc mb --ignore-existing local/sptrans &&
      tail -f /dev/null
      "
    networks: [lab]

volumes:
  nifi_data:
  minio_data:

networks:
  lab: